name: voice_smith
channels:
  - conda-forge
  - defaults
  - pytorch
  - anaconda
  - photosynthesis-team

dependencies:
  - python=3.8
  - flask=2.1.2
  - flask-cors=3.0.10
  - pytorch::torchvision=0.12.0
  - pytorch::torchaudio=0.11.0
  - pytorch::pytorch=1.11.0
  - pytorch::torchtext==0.12.0
  - conda-forge::cudatoolkit=11.3.1
  - psutil=5.9.0
  - einops=0.4.1
  - fire=0.4.0
  - waitress=2.1.1
  - pysoundfile
  - conda-forge::montreal-forced-aligner=2.0.6
  - numpy=1.22.4
  - anaconda::cython=0.29.28
  - conda-forge::torchmetrics=0.9.1
  - conda-forge::spacy=3.3.1
  - photosynthesis-team::piq=0.7.0
  - conda-forge::monkeytype=22.2.0
  - conda-forge::librosa=0.9.2
  - pytest
  - pip
  - pip:
      - -e .
      - tgt==1.4.1
      - nemo-toolkit[all]==1.8.2
      - pythainlp==3.0.8
      - git+https://github.com/savoirfairelinux/num2words.git # Package is not up to date in both pip and conda
